### ISSUE TITLE
Cannot read property 'setHeightCM' of undefined

### ISSUE THREAD

**Issue by Brendan92** [d-band/html2xlsx#12]
I'm exporting only one table which is quite complex but only with 111 rows and 19 columns.

Getting the error:

 TypeError: Cannot read property 'setHeightCM' of undefined
    at Object.<anonymous> (**/node_modules/html2xlsx/lib/index.js:165:23)
    at initialize.exports.each (**/node_modules/cheerio/lib/api/traversing.js:300:24)
    at Object.<anonymous> (**/node_modules/html2xlsx/lib/index.js:36:22)
    at initialize.exports.each (**/node_modules/cheerio/lib/api/traversing.js:300:24)
    at **/node_modules/html2xlsx/lib/index.js:32:16
    at onInline (**/node_modules/juice/index.js:68:12)
    at **/node_modules/web-resource-inliner/src/html.js:256:9
    at **/node_modules/async/dist/async.js:3861:9
    at **/node_modules/async/dist/async.js:421:16
    at eachOfArrayLike (**/node_modules/async/dist/async.js:991:9)
    at eachOf (**/node_modules/async/dist/async.js:1051:5)
    at _parallel (**/node_modules/async/dist/async.js:3852:5)
    at parallelLimit (**/node_modules/async/dist/async.js:3935:5)
    at Object.module.exports [as html] (**/node_modules/web-resource-inliner/src/html.js:254:5)
    at inlineExternal (**/node_modules/juice/index.js:57:10)
    at Function.juiceResources (**/node_modules/juice/index.js:74:3)
    at module.exports (**/node_modules/html2xlsx/lib/index.js:26:19)

Any Ideas on why this will give problems as it is working on all my other tables. I can't seem to find the difference with the data. 

When commenting this line of code in index.js:165, everything works fine...

**Comment by Brendan92** [comment]
This was a problem with the table and empty <tr>
