### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Brendan92** [d-band/html2xlsx#3]
Hi, with some export attempts I get the following error:

 TypeError: Cannot read property 'replace' of undefined
    at replaceInlineAttribute (/Users/***/node_modules/html2xlsx/node_modules/juice/node_modules/web-resource-inliner/src/html.js:19:13)
    at Object.module.exports [as html] (/Users/***/node_modules/html2xlsx/node_modules/juice/node_modules/web-resource-inliner/src/html.js:253:14)
    at inlineExternal (/Users/***/node_modules/html2xlsx/node_modules/juice/index.js:57:10)
    at Function.juiceResources (/Users/***/node_modules/html2xlsx/node_modules/juice/index.js:74:3)
    at module.exports (/Users/***/node_modules/html2xlsx/lib/index.js:26:19)
    at Object.module.exports.index )

I'm not sure what is the cause of this. Hope you can assist me in resolving the problem as it happens on a production environment.

**Comment by Brendan92** [comment]
Found the problem, reading my html as text was taking to long.
